# Variables
compil = gcc
CFLAGS = -Wall -g
fichier_objet = game.o ecriture.o lecture.o utils.o meca.o
cible = game


all: $(cible)

$(cible): $(fichier_objet)
	$(CC) $(CFLAGS) -o $@ $^

# Règle pour générer les fichiers .o à partir des fichiers .c
%.o: %.c
	$(compil) $(CFLAGS) -c $<

# Nettoyage des fichiers générés
clean:
	rm -f $(fichier_objet) $(cible)

# Pour s'assurer que clean est toujours exécutée
.PHONY: all clean
